name: Feature Request
description: Suggest a new feature or improvement
labels: [ enhancement ]
body:
  - type: markdown
    attributes:
      value: |
        Feature requests are welcome!
        Please describe the problem you want to solve.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: What would you like to see?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Optional